dist: xenial
sudo: required

language: go
go: "1.12.x"

jobs:
  include:
    - stage: setup
      script:
        - export PATH="$PATH:$GOPATH/bin"

    # Run a few odo integration tests
    - stage: test
      name: "Registry e2e tests"
      script:
        - ./scripts/get-odo-binary.sh
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - ./scripts/e2e-tests.sh
        - odo logout

    # TODO
    # Run registry integration tests
